services:
  - type: web
    name: my-flask-app
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.app:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true

  - type: web
    name: my-react-app
    env: static
    staticPublishPath: frontend/build
    buildCommand: cd frontend && npm install && npm run build
    plan: free
    healthCheckPath: /
    autoDeploy: true
