"""Initial migration.

Revision ID: 05be42a1a785
Revises: 
Create Date: 2024-07-12 18:42:20.992746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05be42a1a785'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
